# Project identification
sonar.projectKey=yuvidu_ctse-assigment
sonar.organization=yuvidu
sonar.projectName=ctse-assigment
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

# Backend (Spring Boot)
sonar.sources=Booking-Backend/booking-service/src/main/java,Frontend/src

sonar.java.binaries=Booking-Backend/booking-service/target/classes
sonar.java.source=17

# Frontend coverage
sonar.javascript.lcov.reportPaths=Frontend/coverage/lcov.info