# Project identification
sonar.projectKey=yuvidu_ctse-assigment
sonar.organization=yuvidu
sonar.projectName=ctse-assigment
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

# Backend (Spring Boot)
sonar.sources=Booking-Backend/booking-service/src/main/java,User-Backend/user-service/src/main/java

sonar.java.binaries=Booking-Backend/booking-service/target/classes,User-Backend/user-service/target/classes
sonar.java.source=17

# Backend coverage
sonar.coverage.jacoco.xmlReportPaths=Booking-Backend/booking-service/target/site/jacoco/jacoco.xml,User-Backend/user-service/target/site/jacoco/jacoco.xml