spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/users/**
        - id: booking-service
          uri: ${BOOKING_SERVICE_URL:http://localhost:8088}
          predicates:
            - Path=/booking/**
        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/payments/**
        - id: movie-service
          uri: ${MOVIE_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/movies/**
        - id: scheduling-service
          uri: ${SCHEDULING_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/schedules/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            allowedHeaders: "*"

server:
  port: 8087

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO
