spring.application.name=scheduling-service
server.port=${SERVER_PORT:8084}

# MongoDB Configuration
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://yuvidu:yuvidu@cluster1.kt7i4.mongodb.net/microservice?retryWrites=true&w=majority&appName=Cluster1}

# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logging
logging.level.org.springframework.data.mongodb=INFO

# JSON Formatting for Java 8 Dates/Times
spring.jackson.serialization.write-dates-as-timestamps=false
