server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: booking-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://yuvidu:yuvidu@cluster1.kt7i4.mongodb.net/microservice?retryWrites=true&w=majority&appName=Cluster1}

management:
  endpoints:
    web:
      exposure:
        include: health,info

booking:
  admin:
    username: ${BOOKING_ADMIN_USERNAME:admin}
    password: ${BOOKING_ADMIN_PASSWORD:admin-pass}
