name: Trigger auto deployment for booking-service-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ yuvidu-deploy-service-backend ]
    paths:
    - '**'
    - '.github/workflows/booking-service-app-AutoDeployTrigger-c2be3b0c-05dd-45db-ae16-f82bbec32fa2.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.BOOKINGSERVICEAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: bookingacrsliitproject.azurecr.io
          registryUsername: ${{ secrets.BOOKINGSERVICEAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BOOKINGSERVICEAPP_REGISTRY_PASSWORD }}
          containerAppName: booking-service-app
          resourceGroup: booking-rg
          imageToBuild: bookingacrsliitproject.azurecr.io/booking-service-app:${{ github.sha }}
          
            

     

